import type { Env } from '../types'

interface DeployWorkerInput {
  name: string // e.g. "log-report-2026-04-03"
  code: string // JS Worker code to deploy
}

interface DeployResult {
  url: string
  name: string
  deployed: boolean
}

export async function deployWorker(input: DeployWorkerInput, env: Env): Promise<DeployResult> {
  const scriptName = input.name.toLowerCase().replace(/[^a-z0-9-]/g, '-')
  const apiBase = `https://api.cloudflare.com/client/v4/accounts/${env.CF_ACCOUNT_ID}`
  const headers = { Authorization: `Bearer ${env.CF_API_TOKEN}` }

  // 1. Upload the Worker script
  const form = new FormData()
  form.append(
    'metadata',
    JSON.stringify({
      main_module: 'report.js',
      compatibility_date: '2026-01-01',
    }),
  )
  form.append(
    'report.js',
    new Blob([input.code], { type: 'application/javascript+module' }),
    'report.js',
  )

  const uploadRes = await fetch(
    `${apiBase}/workers/scripts/${scriptName}`,
    { method: 'PUT', headers, body: form },
  )

  if (!uploadRes.ok) {
    const err: any = await uploadRes.json()
    throw new Error(`Worker deploy failed: ${JSON.stringify(err.errors)}`)
  }

  // 2. Enable the workers.dev subdomain route
  await fetch(
    `${apiBase}/workers/scripts/${scriptName}/subdomain`,
    {
      method: 'POST',
      headers: { ...headers, 'Content-Type': 'application/json' },
      body: JSON.stringify({ enabled: true }),
    },
  )

  // 3. Get the account's workers.dev subdomain
  const subdomainRes = await fetch(`${apiBase}/workers/subdomain`, { headers })
  const subdomainData: any = await subdomainRes.json()
  const subdomain = subdomainData.result?.subdomain ?? env.CF_ACCOUNT_ID

  return {
    name: scriptName,
    url: `https://${scriptName}.${subdomain}.workers.dev`,
    deployed: true,
  }
}

// Generates a self-contained report Worker from analysis results
export function buildReportWorker(params: {
  title: string
  summary: string
  anomalies: Array<{ time: string; requests: number; zscore: number }>
  chartBase64?: string
}): string {
  return `
export default {
  async fetch(request) {
    const html = ${JSON.stringify(buildReportHtml(params))};
    return new Response(html, {
      headers: { 'Content-Type': 'text/html; charset=utf-8' }
    });
  }
};
`.trim()
}

function buildReportHtml(params: {
  title: string
  summary: string
  anomalies: Array<{ time: string; requests: number; zscore: number }>
  chartBase64?: string
}): string {
  const rows = params.anomalies
    .map(
      (a) => `
      <tr>
        <td>${a.time}</td>
        <td>${a.requests.toLocaleString()}</td>
        <td style="color:${a.zscore > 3 ? '#ef4444' : '#f97316'}">${a.zscore.toFixed(2)}σ</td>
      </tr>`,
    )
    .join('')

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${params.title}</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; background: #0f172a; color: #e2e8f0; }
  h1 { color: #38bdf8; } h2 { color: #94a3b8; font-size: 1rem; font-weight: 500; }
  .summary { background: #1e293b; border-left: 3px solid #38bdf8; padding: 16px; border-radius: 4px; margin: 24px 0; }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; }
  th { text-align: left; padding: 8px 12px; background: #1e293b; color: #94a3b8; font-size: 0.85rem; }
  td { padding: 8px 12px; border-bottom: 1px solid #1e293b; }
  img { max-width: 100%; border-radius: 8px; margin: 24px 0; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 0.75rem; background: #ef4444; color: white; }
</style>
</head>
<body>
  <h1>${params.title}</h1>
  <h2>Generated by Enterprise Log Investigator</h2>
  <div class="summary"><p>${params.summary}</p></div>
  ${params.chartBase64 ? `<img src="data:image/png;base64,${params.chartBase64}" alt="Traffic analysis chart">` : ''}
  <h2>ANOMALIES DETECTED <span class="badge">${params.anomalies.length}</span></h2>
  <table>
    <thead><tr><th>Time (UTC)</th><th>Requests</th><th>Z-Score</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
</body>
</html>`
}
